# generated by datamodel-codegen:
#   filename:  models.schema.json
#   timestamp: 2026-01-09T23:42:19+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, RootModel


class Model(RootModel[Any]):
    root: Any


class Status(str, Enum):
    completed = 'completed'
    failed = 'failed'
    pending = 'pending'


class AnalysisResult(BaseModel):
    analysisType: str
    analysisTypeId: str
    content: str
    createdAt: str
    errorMessage: Optional[str] = None
    llmResponseTimeMs: Optional[float] = None
    promptTokens: Optional[float] = None
    responseTokens: Optional[float] = None
    status: Status


class AnalysisType(BaseModel):
    createdAt: str
    description: str
    icon: str
    id: str
    isActive: bool
    isBuiltIn: bool
    name: str
    partitionKey: str
    prompt: str
    shortTitle: str
    title: str
    type: Optional[str] = None
    updatedAt: str
    userId: Optional[str] = None


class Status1(str, Enum):
    error = 'error'
    success = 'success'


class CreateAnalysisTypeRequest(BaseModel):
    description: str
    icon: str
    name: str
    prompt: str
    shortTitle: str
    title: str


class CreateAnalysisTypeResponse(BaseModel):
    count: Optional[float] = None
    data: Optional[AnalysisType] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status1


class CreateParticipantRequest(BaseModel):
    aliases: Optional[List[str]] = None
    displayName: str
    email: Optional[str] = None
    firstName: Optional[str] = None
    lastName: Optional[str] = None
    notes: Optional[str] = None
    organization: Optional[str] = None
    relationshipToUser: Optional[str] = None
    role: Optional[str] = None


class DeleteAnalysisTypeResponse(BaseModel):
    count: Optional[float] = None
    data: None = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status1


class DeleteParticipantResponse(BaseModel):
    count: Optional[float] = None
    data: None = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status1


class Items(BaseModel):
    manual_upload: Optional[List[str]] = None
    participant: Optional[List[str]] = None
    plaud_recording: Optional[List[str]] = None
    transcription: Optional[List[str]] = None


class DeletedItems(BaseModel):
    createdAt: str
    id: str
    items: Items
    partitionKey: str
    type: Optional[str] = None
    updatedAt: str
    userId: str


class ErrorResponse(BaseModel):
    details: Optional[str] = None
    error: str


class ExecuteAnalysisRequest(BaseModel):
    analysisTypeId: str
    customPrompt: Optional[str] = None
    transcriptionId: str


class ExecuteAnalysisResponse(BaseModel):
    count: Optional[float] = None
    data: Optional[AnalysisResult] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status1


class FailureRecord(BaseModel):
    attemptNumber: int
    error: str
    step: str
    timestamp: str


class GetAnalysisTypesResponse(BaseModel):
    count: float
    data: Optional[List[AnalysisType]] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status1


class Status11(str, Enum):
    completed = 'completed'
    failed = 'failed'
    running = 'running'


class TriggerSource(str, Enum):
    manual = 'manual'
    scheduled = 'scheduled'


class JobExecutionStats(BaseModel):
    chunks_created: int
    errors: int
    recordings_downloaded: int
    recordings_found: int
    recordings_skipped: int
    recordings_transcoded: int
    recordings_uploaded: int
    transcriptions_checked: int
    transcriptions_completed: int
    transcriptions_submitted: int


class Level(str, Enum):
    debug = 'debug'
    error = 'error'
    info = 'info'
    warning = 'warning'


class JobLogEntry(BaseModel):
    level: Level
    message: str
    recordingId: Optional[str] = None
    timestamp: str


class Status12(str, Enum):
    dismissed = 'dismissed'
    in_progress = 'in_progress'
    pending = 'pending'
    resolved = 'resolved'


class ManualReviewItem(BaseModel):
    assignedTo: Optional[str] = None
    createdAt: str
    failureCount: int
    failureHistory: List[FailureRecord]
    id: str
    lastError: str
    partitionKey: str
    recordingId: str
    recordingTitle: str
    resolution: Optional[str] = None
    resolvedAt: Optional[str] = None
    status: Status12
    testRunId: Optional[str] = None
    type: Optional[str] = None
    updatedAt: str
    userId: str


class MergeFields(BaseModel):
    aliases: Optional[List[str]] = None
    displayName: Optional[str] = None
    notes: Optional[str] = None


class MergeParticipantsRequest(BaseModel):
    merge_fields: Optional[MergeFields] = None


class Status13(str, Enum):
    error = 'error'
    success = 'success'


class Participant(BaseModel):
    aliases: List[str]
    createdAt: str
    displayName: str
    email: Optional[str] = None
    firstName: Optional[str] = None
    firstSeen: str
    id: str
    isUser: Optional[bool] = None
    lastName: Optional[str] = None
    lastSeen: str
    notes: Optional[str] = None
    organization: Optional[str] = None
    partitionKey: str
    relationshipToUser: Optional[str] = None
    role: Optional[str] = None
    type: Optional[str] = None
    updatedAt: str
    userId: str


class PlaudMetadata(BaseModel):
    originalTimestamp: str
    plaudDuration: float
    plaudFileSize: float
    plaudFileType: str
    plaudFilename: str
    plaudId: str
    syncedAt: str


class PlaudSettings(BaseModel):
    activeSyncStarted: Optional[str] = None
    activeSyncToken: Optional[str] = None
    bearerToken: str
    enableSync: Optional[bool] = None
    lastSyncTimestamp: Optional[str] = None


class PlaudSettingsResponse(BaseModel):
    plaudSettings: PlaudSettings


class PlaudSyncResponse(BaseModel):
    dry_run: bool
    message: str
    sync_token: str


class PlaudSyncStatusResponse(BaseModel):
    activeSyncToken: Optional[str] = None
    currentSyncActive: bool
    hasSettings: bool
    lastSyncTimestamp: Optional[str] = None
    syncEnabled: bool


class Source(str, Enum):
    plaud = 'plaud'
    stream = 'stream'
    upload = 'upload'


class TranscodingStatus(str, Enum):
    completed = 'completed'
    failed = 'failed'
    in_progress = 'in_progress'
    not_started = 'not_started'
    queued = 'queued'


class TranscriptionJobStatus(str, Enum):
    completed = 'completed'
    failed = 'failed'
    not_started = 'not_started'
    processing = 'processing'
    submitted = 'submitted'


class TranscriptionStatus(str, Enum):
    completed = 'completed'
    failed = 'failed'
    in_progress = 'in_progress'
    not_started = 'not_started'


class RecordingParticipant(BaseModel):
    confidence: float
    displayName: str
    manuallyVerified: bool
    participantId: str
    speakerLabel: str


class SearchParticipantsResponse(BaseModel):
    count: Optional[float] = None
    data: Optional[List[Participant]] = None
    error: Optional[str] = None
    fuzzy_search: bool
    message: Optional[str] = None
    search_term: str
    status: Status13


class Status15(str, Enum):
    completed = 'completed'
    failed = 'failed'
    processing = 'processing'
    queued = 'queued'


class SyncProgress(BaseModel):
    currentStep: str
    errors: List[str]
    estimatedCompletion: Optional[str] = None
    failedRecordings: float
    id: str
    lastUpdate: str
    partitionKey: str
    processedRecordings: float
    startTime: str
    status: Status15
    syncToken: str
    totalRecordings: Optional[float] = None
    ttl: Optional[float] = None
    type: Optional[str] = None
    userId: str


class T(BaseModel):
    pass


class Tag(BaseModel):
    color: str
    id: str
    name: str


class SpeakerMapping(BaseModel):
    confidence: Optional[float] = None
    displayName: Optional[str] = None
    manuallyVerified: Optional[bool] = None
    name: Optional[str] = None
    participantId: Optional[str] = None
    reasoning: Optional[str] = None


class Transcription(BaseModel):
    analysisResults: Optional[List[AnalysisResult]] = None
    az_raw_transcription: Optional[str] = None
    az_transcription_id: Optional[str] = None
    diarized_transcript: Optional[str] = None
    id: str
    partitionKey: str
    recording_id: str
    speaker_mapping: Optional[Dict[str, SpeakerMapping]] = None
    testRunId: Optional[str] = None
    text: Optional[str] = None
    token_count: Optional[float] = None
    transcript_json: Optional[str] = None
    type: Optional[str] = None
    user_id: str


class UpdateAnalysisTypeRequest(BaseModel):
    description: Optional[str] = None
    icon: Optional[str] = None
    isActive: Optional[bool] = None
    prompt: Optional[str] = None
    shortTitle: Optional[str] = None
    title: Optional[str] = None


class Status16(str, Enum):
    error = 'error'
    success = 'success'


class UpdateAnalysisTypeResponse(BaseModel):
    count: Optional[float] = None
    data: Optional[AnalysisType] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status16


class UpdateLastSeenRequest(BaseModel):
    timestamp: Optional[str] = None


class UpdateParticipantRequest(BaseModel):
    aliases: Optional[List[str]] = None
    displayName: Optional[str] = None
    email: Optional[str] = None
    firstName: Optional[str] = None
    isUser: Optional[bool] = None
    lastName: Optional[str] = None
    notes: Optional[str] = None
    organization: Optional[str] = None
    relationshipToUser: Optional[str] = None
    role: Optional[str] = None


class UpdateParticipantResponse(BaseModel):
    count: Optional[float] = None
    data: Optional[Participant] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status16


class User(BaseModel):
    azure_oid: Optional[str] = None
    created_at: Optional[str] = None
    email: Optional[str] = None
    id: str
    is_test_user: Optional[bool] = None
    last_login: Optional[str] = None
    name: Optional[str] = None
    partitionKey: str
    plaudSettings: Optional[PlaudSettings] = None
    role: Optional[str] = None
    tags: Optional[List[Tag]] = None
    type: Optional[str] = None


class Integer(RootModel[float]):
    root: float


class ActiveSyncCheckResponse(BaseModel):
    has_active_sync: bool
    progress: Optional[SyncProgress] = None
    sync_token: Optional[str] = None


class ApiResponse(BaseModel):
    count: Optional[float] = None
    data: Optional[T] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status1


class CreateParticipantResponse(BaseModel):
    count: Optional[float] = None
    data: Optional[Participant] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status1


class GetParticipantResponse(BaseModel):
    count: Optional[float] = None
    data: Optional[Participant] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status1


class GetParticipantsResponse(BaseModel):
    count: float
    data: Optional[List[Participant]] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status1


class JobExecution(BaseModel):
    duration: Optional[int] = None
    durationFormatted: Optional[str] = None
    endTime: Optional[str] = None
    errorMessage: Optional[str] = None
    id: str
    logs: Optional[List[JobLogEntry]] = None
    partitionKey: str
    startTime: str
    stats: JobExecutionStats
    status: Status11
    testRunId: Optional[str] = None
    triggerSource: TriggerSource
    ttl: int
    type: Optional[str] = None
    userId: Optional[str] = None
    usersProcessed: Optional[List[str]] = None


class MergeParticipantsResponse(BaseModel):
    count: Optional[float] = None
    data: Optional[Participant] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status13


class Recording(BaseModel):
    az_transcription_id: Optional[str] = None
    chunkGroupId: Optional[str] = None
    description: Optional[str] = None
    duration: Optional[float] = None
    id: str
    is_dummy_recording: Optional[bool] = None
    last_check_time: Optional[str] = None
    last_failure_message: Optional[str] = None
    needs_manual_review: Optional[bool] = None
    original_filename: str
    participants: Optional[Union[List[str], List[RecordingParticipant]]] = None  # DEPRECATED: Use transcription.speaker_mapping instead
    partitionKey: str
    plaudMetadata: Optional[PlaudMetadata] = None
    processing_failure_count: Optional[int] = None
    recorded_timestamp: Optional[str] = None
    source: Optional[Source] = None
    tagIds: Optional[List[str]] = None
    testRunId: Optional[str] = None
    title: Optional[str] = None
    token_count: Optional[float] = None
    transcoding_completed_at: Optional[str] = None
    transcoding_error_message: Optional[str] = None
    transcoding_retry_count: Optional[int] = None
    transcoding_started_at: Optional[str] = None
    transcoding_status: Optional[TranscodingStatus] = None
    transcoding_token: Optional[str] = None
    transcription_error_message: Optional[str] = None
    transcription_id: Optional[str] = None
    transcription_job_id: Optional[str] = None
    transcription_job_status: Optional[TranscriptionJobStatus] = None
    transcription_status: Optional[TranscriptionStatus] = None
    transcription_status_updated_at: Optional[str] = None
    type: Optional[str] = None
    unique_filename: str
    upload_timestamp: Optional[str] = None
    user_id: str


class GetParticipantRecordingsResponse(BaseModel):
    count: Optional[float] = None
    data: Optional[List[Recording]] = None
    error: Optional[str] = None
    message: Optional[str] = None
    status: Status1
    total: float
