services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    env_file:
      - ./backend/.env.local
    volumes:
      - ./backend:/app
    networks:
      - quickscribe-network

  frontend:
    build:
      context: ./frontend_new
      dockerfile: Dockerfile
    user: "${UID:-$(id -u)}:${GID:-$(id -g)}"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./frontend_new/.env
    volumes:
      - ./frontend_new:/app
      - ./shared:/shared
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - quickscribe-network

  transcoder:
    build:
      context: ./transcoder_container
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./transcoder_container/.env.local
    volumes:
      - ./transcoder_container:/app
    networks:
      - quickscribe-network

volumes:
  frontend_node_modules:

networks:
  quickscribe-network:
    driver: bridge