# generated by datamodel-codegen:
#   filename:  models.schema.json
#   timestamp: 2025-06-03T21:41:47+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, RootModel


class Model(RootModel[Any]):
    root: Any


class PlaudMetadata(BaseModel):
    originalTimestamp: str
    plaudDuration: float
    plaudFileSize: float
    plaudFileType: str
    plaudFilename: str
    plaudId: str
    syncedAt: str


class PlaudSettings(BaseModel):
    activeSyncStarted: Optional[str] = None
    activeSyncToken: Optional[str] = None
    bearerToken: str
    enableSync: Optional[bool] = None
    lastSyncTimestamp: Optional[str] = None


class Source(str, Enum):
    plaud = 'plaud'
    stream = 'stream'
    upload = 'upload'


class TranscodingStatus(str, Enum):
    completed = 'completed'
    failed = 'failed'
    in_progress = 'in_progress'
    not_started = 'not_started'
    queued = 'queued'


class TranscriptionStatus(str, Enum):
    completed = 'completed'
    failed = 'failed'
    in_progress = 'in_progress'
    not_started = 'not_started'


class Recording(BaseModel):
    az_transcription_id: Optional[str] = None
    duration: Optional[float] = None
    id: str
    original_filename: str
    partitionKey: str
    plaudMetadata: Optional[PlaudMetadata] = None
    source: Optional[Source] = None
    transcoding_completed_at: Optional[str] = None
    transcoding_error_message: Optional[str] = None
    transcoding_retry_count: Optional[int] = None
    transcoding_started_at: Optional[str] = None
    transcoding_status: Optional[TranscodingStatus] = None
    transcoding_token: Optional[str] = None
    transcription_error_message: Optional[str] = None
    transcription_id: Optional[str] = None
    transcription_status: Optional[TranscriptionStatus] = None
    transcription_status_updated_at: Optional[str] = None
    unique_filename: str
    upload_timestamp: Optional[str] = None
    user_id: str


class SpeakerMapping(BaseModel):
    name: str
    reasoning: str


class Transcription(BaseModel):
    az_raw_transcription: Optional[str] = None
    az_transcription_id: Optional[str] = None
    diarized_transcript: Optional[str] = None
    id: str
    partitionKey: str
    recording_id: str
    speaker_mapping: Optional[Dict[str, SpeakerMapping]] = None
    text: Optional[str] = None
    transcript_json: Optional[str] = None
    user_id: str


class User(BaseModel):
    created_at: Optional[str] = None
    email: Optional[str] = None
    id: str
    is_test_user: Optional[bool] = None
    last_login: Optional[str] = None
    name: Optional[str] = None
    partitionKey: str
    plaudSettings: Optional[PlaudSettings] = None
    role: Optional[str] = None


class Integer(RootModel[float]):
    root: float
