import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const sharedModelsPath = path.join(__dirname, '../../shared/Models.ts');
const frontendTypesPath = path.join(__dirname, '../src/types/models.ts');

console.log('Syncing models from shared/Models.ts...');

if (!fs.existsSync(sharedModelsPath)) {
  console.error('Error: shared/Models.ts not found at', sharedModelsPath);
  process.exit(1);
}

// Read shared models
const sharedModels = fs.readFileSync(sharedModelsPath, 'utf8');

// Add header comment
const output = `// AUTO-GENERATED from /shared/Models.ts
// Do not edit this file directly - changes will be overwritten
// Last synced: ${new Date().toISOString()}

${sharedModels}
`;

// Ensure types directory exists
const typesDir = path.dirname(frontendTypesPath);
if (!fs.existsSync(typesDir)) {
  fs.mkdirSync(typesDir, { recursive: true });
}

// Write to frontend types
fs.writeFileSync(frontendTypesPath, output, 'utf8');

console.log('✓ Models synced successfully to src/types/models.ts');
