# generated by datamodel-codegen:
#   filename:  types.schema.json
#   timestamp: 2024-10-29T21:36:27+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any


class TranscriptionStatus(Enum):
    completed = 'completed'
    failed = 'failed'
    in_progress = 'in_progress'
    not_started = 'not_started'


class Recording(BaseModel):
    az_transcription_id: Optional[str] = None
    duration: Optional[float] = None
    id: Optional[str] = None
    original_filename: Optional[str] = None
    transcription_error_message: Optional[str] = None
    transcription_status: Optional[TranscriptionStatus] = None
    transcription_status_updated_at: Optional[str] = None
    unique_filename: Optional[str] = None
    user_id: Optional[str] = None


class SpeakerMapping(BaseModel):
    name: Optional[str] = None
    reasoning: Optional[str] = None


class Transcription(BaseModel):
    az_raw_transcription: Optional[str] = None
    diarized_transcript: Optional[str] = None
    id: Optional[str] = None
    recording_id: Optional[str] = None
    speaker_mapping: Optional[Dict[str, SpeakerMapping]] = None
    text: Optional[str] = None
    transcript_json: Optional[str] = None
    user_id: Optional[str] = None


class User(BaseModel):
    email: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
